---
title: "Portfolio 4: Plastic, plastic, redux"
format:
  html:
    embed-resources: true
---

## Introduction

For this portfolio you'll be revisiting the chart you submitted for portfolio 1, producing a new version of the chart incorporating some of what you have learnt in weeks 1-4.

## Requirements

Download the `portfolio04.qmd` template file below and copy/paste your original code from your `portfolio01.qmd` into the first code block.

Use the space provided to write a short plan of what you wish to improve on the chart and why you think those changes are important. You are welcome to utilise (or ignore!) the feedback you received for portfolio 1. Two to three sentences will suffice and you are welcome to incorporate bullet points or a list if that helps keep your writing concise.

Then utilise the second code block to produce a new, revised chart based on your plan.

 - Your original chart should be left unchanged. Same code, same output dimensions etc.
 - There are no restrictions on what you can change in your revised version. You could produce a completely different chart (different geometry etc) if you feel that is better and have explained why in your plan.
 - As always, your chart must have appropriate labels.
 - Your chart should have a useful title or subtitle that directs the reader at the key 'story'.
 - Your code for both the original chart and your revised chart should both be present in the rendered document.
 - You should ensure the revised chart in your final document is appropriately dimensioned and readable: the original chart should be left as it was.
 
**Our expectation is this should take you approximately one hour.** You may spend more or less time than this if you wish, but there is no need to do so if your chart satisfies the criteria above.

::: {.callout-note collapse="true" appearance="simple"}

### Grading rubric

You will be graded out of 10 based on:

|  |  |  |
|---------|---------------------------------------------------------|------|
| **Plan** | Your .qmd file renders correctly without errors or warnings | 3 |
|  | Your .qmd file renders but has warnings | 2 |
|  | Your .qmd file renders but has warnings | 1 |
|  | Your .qmd file doesn't render without modification | 0 |
| **Code** | Your name is in the author field and all necessary code is visible in the rendered document | 3 |
|  | Your code is visible in the rendered document but your name is missing | 2 |
|  | Your code is visible in the rendered document but your name is missing | 1 |
|  | Both code and name are missing | 0 |
| **Chart** | Your chart satisfies all criteria and is well labelled | 4 |
|  | Your chart satisfies all criteria but has a minor flaw with labelling or dimensions | 5 |
|  | Your chart satisfies all criteria but has multiple minor flaws or uses sub-optimal geometry | 4 |
|  | Your chart has major flaws, is missing criteria or is confusing | 3 |
|  | Your chart is inappropriate or incomprehensible | 1 |
|  | Missing or entirely incorrect | 0 |

:::

## Template file

Download your template file by right clicking and selecting Save File As...

<https://www.massey.ac.nz/~jcmarsha/161307/portfolio/portfolio04.qmd>
