---
title: "Portfolio 1: Plastic, plastic, everywhere"
format:
  html:
    embed-resources: true
---

## Introduction

Recall from Workshop 1 that LEGO enthusiasts have noted that sets have increased detail and complexity which results in more parts but potentially similar amounts of plastic.

In this portfolio your goal is to produce a figure to demonstrate whether the amount of plastic in LEGO sets for a given price is changing over time.

We use data on `lego_sets` and `lego_parts` joined together:

```{r}
#| message: false
#| echo: true

library(tidyverse)

lego_sets <- read_csv("https://www.massey.ac.nz/~jcmarsha/data/lego/lego_sets.csv")
lego_parts <- read_csv("https://www.massey.ac.nz/~jcmarsha/data/lego/lego_parts.csv.gz")

set_weights <- lego_parts |>
  group_by(set) |>
  summarise(weight = sum(weight*quantity, na.rm=TRUE))

sets_with_weight <- lego_sets |>
  left_join(set_weights, by=join_by(set))
```

## Requirements

Download the `portfolio01.qmd` template file below and write code using the `sets_with_weight` data to produce ONE chart of price per gram for each lego set for each theme for each year.

**You should model it on the chart we did in workshop 1 which related `price_per_part` to `year` and `theme`.**

 - Ensure you fill in your name in the author field.
 - Ensure you have a facetted plot (facet by theme is recommended).
 - Show both the data and a trend on each facet.
 - Your chart should have appropriate labels, a title and subtitle.
 - Use the title to help tell the story of the chart.
 - You should submit the `portfolio01.qmd` file to the stream dropbox.
 - Make sure that it renders correctly before submission.

**Our expectation is this should take you approximately one hour.** You may spend more or less time than this if you wish, but there is no need to do so if your chart satisfies the criteria above.

::: {.callout-note collapse="true" appearance="simple"}

### Grading rubric

You will be graded out of 10 based on:

|  |  |  |
|---------|---------------------------------------------------------|------|
| **Reproducibility** | Your .qmd file renders correctly without errors or warnings | 2 |
|  | Your .qmd file renders but has warnings | 1 |
|  | Your .qmd file doesn't render without modification | 0 |
| **Code/Authorship** | Your name is in the author field and all necessary code is visible in the rendered document | 2 |
|  | Your code is visible in the rendered document but your name is missing | 1 |
|  | Both code and name are missing | 0 |
| **Chart** | Your chart satisfies all criteria and is well labelled | 6 |
|  | Your chart satisfies all criteria but has a minor flaw with labelling or dimensions | 5 |
|  | Your chart satisfies all criteria but has multiple minor flaws or uses sub-optimal geometry | 4 |
|  | Your chart has major flaws, is missing criteria or is confusing | 3 |
|  | Your chart is inappropriate or incomprehensible | 1 |
|  | Missing or entirely incorrect | 0 |

:::

## Template file

Download your template file by right clicking and selecting Save File As...

<https://www.massey.ac.nz/~jcmarsha/161307/portfolio/portfolio01.qmd>
