---
title: "Portfolio 3: Joyous Births"
format:
  html:
    embed-resources: true
---

## Introduction

For this portfolio we'll be recreating one of the classic "ridge-line" plots or "joy plots" that show changes in mothers age of birth through time.

This is usually done with US data to highlight the baby boom, but we'll be using the Aotearoa/NZ data instead, by cohort:

```{r}
#| message: false
library(tidyverse)

nz_births <- read_csv("https://www.massey.ac.nz/~jcmarsha/data/nz/births_tidy.csv") |>
  mutate(cohort = year - age) |> # mothers year of birth
  filter(cohort >= 1948, cohort <= 1980, age < 46)
```


## Requirements

Download the `portfolio03.qmd` template file below and **modify** the existing figure code to produce a unique, eye-catching chart with the same geometry type.

 - Ensure you fill in your name in the author field.
 - Keep the same geometry (`geom_slab()`) but instead focus on the presentation.
 - Your chart must have appropriate labels and a title.
 - You must use a theme for your chart that is unique: any pre-existing theme used must be modified.
 - You must utilise a non-standard font which is acquired via `require_font()` from an online source (for reproducibility).
 - You must utilise a colour in your chart in some way. This needn't be mapped to an aesthetic (though can be if you wish).
 - You must alter the aspect ratio or dimensions of the figure.
 - You should submit the `portfolio03.qmd` file to the stream dropbox.
 - Make sure that it renders correctly before submission.
 
**Our expectation is this should take you approximately one hour.** You may spend more or less time than this if you wish, but there is no need to do so if your chart satisfies the criteria above.

::: {.callout-note collapse="true" appearance="simple"}

### Grading rubric

You will be graded out of 10 based on:

|  |  |  |
|---------|---------------------------------------------------------|------|
| **Reproducibility** | Your .qmd file renders correctly without errors or warnings | 2 |
|  | Your .qmd file renders but has warnings | 1 |
|  | Your .qmd file doesn't render without modification | 0 |
| **Code/Authorship** | Your name is in the author field and all necessary code is visible in the rendered document | 2 |
|  | Your code is visible in the rendered document but your name is missing | 1 |
|  | Both code and name are missing | 0 |
| **Chart** | Your chart satisfies all criteria and is well labelled | 6 |
|  | Your chart satisfies all criteria but has a minor flaw with labelling or dimensions | 5 |
|  | Your chart satisfies all criteria but has multiple minor flaws or uses sub-optimal geometry | 4 |
|  | Your chart has major flaws, is missing criteria or is confusing | 3 |
|  | Your chart is inappropriate or incomprehensible | 1 |
|  | Missing or entirely incorrect | 0 |

:::

## Template file

Download your template file by right clicking and selecting Save File As...

<https://www.massey.ac.nz/~jcmarsha/161307/portfolio/portfolio03.qmd>
