---
title: "Portfolio 2: Daily use of He Ara Kotahi bridge"
format:
  html:
    embed-resources: true
---

## Introduction

For this portfolio you'll be creating a visualisation of the distribution of the number of people using the bridge on He Ara Kotahi walkway per day in Palmerston North.

We use data from one year which we've summarised by all users per day:

```{r}
#| message: false
library(tidyverse)
walk_cycle <- read_csv("https://www.massey.ac.nz/~jcmarsha/data/pncc_cycle_counts/he_ara_kotahi_one_year.csv") |>
  group_by(Date) |>
  summarise(Count = sum(Count)) |>
  mutate(Day = wday(Date, label=TRUE))
```

## Requirements

Download the `portfolio02.qmd` template file below and write code using the `walk_cycle` data to produce ONE chart of the **distribution** of the number of people using the bridge per day.

**It is your choice as to which chart type you choose to use. There is not necessarily a "best" chart type.**

 - Ensure you fill in your name in the author field.
 - Your chart should clearly show the **distribution** of the number of people using the bridge for each of the 7 days separately.
 - Consider carefully what the "story" of your chart is and use the title/subtitle or annotation to help highlight the story.
 - Ensure your chart has clear labels.
 - You should submit the `portfolio02.qmd` file to the stream dropbox.
 - Make sure that it renders correctly before submission.

**Our expectation is this should take you approximately one hour.** You may spend more or less time than this if you wish, but there is no need to do so if your chart satisfies the criteria above.

::: {.callout-note collapse="true" appearance="simple"}

### Grading rubric

You will be graded out of 10 based on:

|  |  |  |
|---------|---------------------------------------------------------|------|
| **Reproducibility** | Your .qmd file renders correctly without errors or warnings | 2 |
|  | Your .qmd file renders but has warnings | 1 |
|  | Your .qmd file doesn't render without modification | 0 |
| **Code/Authorship** | Your name is in the author field and all necessary code is visible in the rendered document | 2 |
|  | Your code is visible in the rendered document but your name is missing | 1 |
|  | Both code and name are missing | 0 |
| **Chart** | Your chart satisfies all criteria and is well labelled | 6 |
|  | Your chart satisfies all criteria but has a minor flaw with labelling or dimensions | 5 |
|  | Your chart satisfies all criteria but has multiple minor flaws or uses sub-optimal geometry | 4 |
|  | Your chart has major flaws, is missing criteria or is confusing | 3 |
|  | Your chart is inappropriate or incomprehensible | 1 |
|  | Missing or entirely incorrect | 0 |

:::

## Template file

Download your template file by right clicking and selecting Save File As...

<https://www.massey.ac.nz/~jcmarsha/161307/portfolio/portfolio02.qmd>
