---
title: "Workshop 1: Remember all the things"
format: html
---

## Purpose of the workshops

The purpose of the workshops is two fold:

1. That you learn to create visualisations in a reproducible way.
2. That you **understand** the principles behind creating visualisations in a reproducible way.

The **understanding** aspect is crucial! We don't want you to just run the code, skim the commentary and complete the **Try yourself** sections. Instead it's important to take the time to add notes of your own, to experiment with different features of the software, and to make sure you understand what you're doing and why!

Your skill set in creating high quality data visualisations will come down to how much time you dedicate to becoming proficient!

## Before you start

Make sure you have both R and RStudio installed. In addition, make sure you have the `tidyverse` package installed.

Both of these are detailed here:

<https://r-resources.massey.ac.nz/help/usingrin297.101.html>

## Creating a project for your work

RStudio projects are basically just a folder on your computer where you can store your work.

We recommend creating an RStudio project that you can utilise for all the 161307 workshops.

1. Open RStudio.
2. Click on the "File" menu at the top and select "New Project..."
3. Select "New Directory" and then "New Project".
4. Type in the name of the project you want (e.g. "161307")
5. Optionally select Browser to change where you'd like that stored on you computer.
6. Select "Create project"

This will add a new subfolder "161307" to the folder you selected in step 5 and RStudio will load up the project in that folder. You should see in the Files tab in the bottom right where that folder is located.

## Download the workshop .qmd

Now download `lab01.qmd` into this folder.

The easiest way to do this is to right click on the URL below and "Save file as..."

<https://www.massey.ac.nz/~jcmarsha/161307/labs/lab01.qmd>

Save it into the 161307 folder you created above.

Go back to RStudio and you'll see the `lab01.qmd` file in the `Files` tab in bottom right.

Click on it to load it up and then work through the workshop.

**Remember to take lots of notes and to ask questions of the teaching staff if there's anything you find unclear.**
