---
title: "Workshop 3: Tidying up"
format: html
---

There are two goals of todays workshop:

1. Take a look at obtaining some real data from Statistics NZ, and tidying it up.

2. Tidying up plots by looking at themes, fonts and sizing and adding annotation.

Both of these are really important: data just about never comes in the form you've likely seen to date in your statistics education - it's hardly ever nice and tidy and thus needs a little (or a lot) of janitor work to get it cleaned up and ready for analysis or presentation.

The second is just as important: Charts that are aesthetically pleasing are nicer to look at, but equally need to be readable, so sizing of various elements of the chart are important to ensure labels aren't too large or too small, that font use is consistent where practical, and that multiple charts in a series are consistent in their use of colour, labels, fonts and so on.

Start by downloading lab03.qmd into your 161307 project folder

<https://www.massey.ac.nz/~jcmarsha/161307/labs/lab02.qmd>

Open your 161307 project in RStudio and then load up `lab03.qmd` and work through the workshop.

**Remember to take lots of notes and to ask questions of the teaching staff if there's anything you find unclear.**
